import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
const inter = Inter({ subsets: ["latin"] });
import {SidebarProvider} from '../context/index';

export const metadata = {
  title: "HomePage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SidebarProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar/>
          <Sidebar/>
          {children}
        </body>
      </html>
    </SidebarProvider>
  );
}